<%--

$Id: changeIdentity.jsp 1053 2010-11-16 12:06:55Z dmckain $

Copyright (c) 2010, The University of Edinburgh.
All Rights Reserved

@author  David McKain
@version $Revision: 1053 $

--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="title" value="ASCIIMathML Verified Input Demo" />
<c:set var="pageId" value="asciiMathInputDemo" />

<%@ include file="/WEB-INF/jsp/includes/header.jspf" %>

<script type="text/javascript">//<![CDATA[
  jQuery(document).ready(function() {
    VerifierController.setValidatorServiceUrl('ASCIIMathUpConversionService');
    VerifierController.setDelay(500);

    var verifierControl = VerifierController.createVerifierControl();
    verifierControl.setVerifiedRenderingContainerId('verifiedRendering');
    verifierControl.setCMathSourceContainerId('cmathSource');
    verifierControl.setMaximaSourceContainerId('maximaSource');

    var widget = ASCIIMathInputController.createInputWidget('asciiMathInputControl', 'asciiMathOutputControl', verifierControl);
    widget.setPMathSourceContainerId('pmathSource');
    widget.setMathJaxRenderingContainerId('mathJaxRendering');
    widget.init();
  });
//]]></script>
<h2>ASCIIMath Verified Input Demo</h2>
<p>
  This demo shows the use of ASCIIMathML as an input format for the kind of
  simple maths we might expect from a 16-18 year-old student in the UK. The resulting
  input is rendered using MathJax and is then passed to the SnuggleTeX semantic
  enrichment code for conversion to Content MathML and Maxima input syntax.
  The input is deemed to "make sense" if this process succeeds. The resulting
  semantic representation of the input can then be used by an assessment system,
  or something similar.
</p>
<h3>ASCIIMath Input</h3>
<p>
  Enter some ASCIIMath in the box below:
</p>
<form action="ASCIIMathInputDemo" method="post" class="input">
  <div class="inputBox">
    <input id="asciiMathInputControl" name="asciiMathInput" type="text" value="${asciiMathInput}">
    <input id="asciiMathOutputControl" name="asciiMathOutput" type="hidden">
    <input type="submit" value="Submit">
  </div>
</form>

<h3>ASCIIMathML Rendering</h3>
<p>This shows a client-side rendering of the input using MathJax:</p>
<div id="mathJaxRendering"></div>

<h3>Verified MathML</h3>
<p>This shows the results of "verifying" the input to see if it "makes sense".</p>
<div id="verifiedRendering"></div>

<h3>Resulting ASCIIMathML source</h3>
<p>For geeks, this is the raw MathML generated by ASCIIMath</p>
<pre class="result" id="pmathSource"></pre>

<h3>Resulting Content MathML source</h3>
<p>This is the resulting Content MathML, created by the verification service.</p>
<pre class="result" id="cmathSource"></pre>

<h3>Resulting Maxima code</h3>
<p>This is the resulting Maxima input syntax, created by the verification service.</p>
<pre class="result" id="maximaSource"></pre>

<%@ include file="/WEB-INF/jsp/includes/footer.jspf" %>
