<%--

$Id$

Copyright (c) 2011, The University of Edinburgh.
All Rights Reserved

@author  David McKain
@version $Revision: 1053 $

--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<c:set var="title" value="Server-side ASCIIMath Demo" />
<c:set var="pageId" value="serverSideasciiMathDemo" />

<%@ include file="/WEB-INF/jsp/includes/header.jspf" %>

<h1>Server-side ASCIIMath Input Demo</h2>

<h2>ASCIIMath Input</h2>
<p>
  Enter some ASCIIMath in the box below:
</p>
<form action="server-side-asciimath-demo" method="post" class="input">
  <div class="inputBox">
    <input name="asciiMathInput" type="text" value="${asciiMathInput}">
    <input type="submit" value="Submit">
  </div>
</form>

<c:if test="${!empty mathMLOutput}">
  <h2>MathML Output (from server)</h2>

  <p>
    This is the MathML generated by running ASCIIMath <em>on the web server</em>.
    There is no JavaScript in this demo at all!
  </p>

  <pre class="result">${fn:escapeXml(mathMLOutput)}</pre>
</c:if>

<%@ include file="/WEB-INF/jsp/includes/footer.jspf" %>
