<%--

$Id$

Copyright (c) 2011, The University of Edinburgh.
All Rights Reserved

@author  David McKain
@version $Revision$

--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="title" value="SnuggleTeX semantic input widget demo" />
<c:set var="pageId" value="snuggleTeXInputDemo" />
<c:set var="headStuff">
  <link rel="stylesheet" type="text/css" href="<c:url value='includes/upconversion-ajax-control.css'/>">
  <script type="text/javascript" src="<c:url value='includes/jquery/jquery-1.5.1.js'/>"></script>
  <script type="text/javascript" src="<c:url value='includes/UpConversionAJAXController.js'/>"></script>
  <script type="text/javascript" src="<c:url value='includes/SnuggleTeXInputController.js'/>"></script>
  <%@ include file="/WEB-INF/jsp/includes/mathjax.jspf" %>
</c:set>

<%@ include file="/WEB-INF/jsp/includes/header.jspf" %>

<!-- TEST -->
<script type="text/javascript">//<![CDATA[
  jQuery(document).ready(function() {
    UpConversionAJAXController.setUpConversionServiceUrl('<c:url value="/snuggletex-upconversion-service"/>');
    UpConversionAJAXController.setDelay(500);

    var upConversionAJAXControl = UpConversionAJAXController.createUpConversionAJAXControl();
    upConversionAJAXControl.setBracketedRenderingContainerId('previewRendering');
    upConversionAJAXControl.setPMathSemanticSourceContainerId('pmathSemanticSource');
    upConversionAJAXControl.setPMathBracketedSourceContainerId('pmathBracketedSource');
    upConversionAJAXControl.setCMathSourceContainerId('cmathSource');
    upConversionAJAXControl.setMaximaSourceContainerId('maximaSource');

    var widget = SnuggleTeXInputController.createInputWidget('latexInputControl', upConversionAJAXControl);
    widget.init();
  });
//]]></script>

<h1>SnuggleTeX semantic input widget demo</h1>

<p>
  This is basically the same as the
  <a href="asciimath-semantic-input-demo">ASCIIMath semantic input widget demo</a>,
  but it uses LaTeX as an input format, which is processed using SnuggleTeX.
</p>
<p>
  This demo is arguably not as successful as the ASCIIMath demo,
  as the SnuggleTeX parser is very strict so will complain about incomplete
  expressions, so can lead to a lot of negative feedback.
</p>

<h2>Try it</h2>
<p>
  Enter some LaTeX in the box below. Feedback will be shown while you type
  to the right of the input box. Some additional technical details will appear
  below that may be interesting to some people...
</p>
<div class="inputBox inputWidget">
  <div class="inputPanel">
    <form action="snuggletex-semantic-input-demo" method="post" class="input">
      <input id="latexInputControl" name="latexMathInput" type="text" value="${latexMathInput}">
      <input type="submit" value="Submit">
    </form>
  </div>
  <div class="previewPanel">
    <div id="previewRendering"></div>
  </div>
</div>
<p>
  This input widget is configured to treat <b>f</b> and <b>g</b> as functions,
  <b>e</b> as the exponential number, <b>i</b> as the imaginary number and
  <b>&#x3b3;</b> as Euler's constant.
</p>

<h2>Technical implementation details</h2>

<p>
  The LaTeX input syntax is sent to a simple AJAX web service that converts it
  to Presentation MathML using SnuggleTeX, and then applies the SnuggleTeX
  semantic enrichment process on it to see if it can be converted to Content MathML
  (and Maxima input syntax). It also converts it to a special "bracketed" version
  of Presentation MathML, which is shown next to the input box above, using MathJax
  for rendering so that it works in most modern browsers.
</p>
<p>
  MathML experts may be interested in the live information below.
</p>

<h3>Semantic Presentation MathML generated by SnuggleTeX</h3>
<p>
  This shows the result of the first part of the SnuggleTeX semantic enrichment process,
  which restructures the raw Presentation MathML to emphasise the underlying semantics
  and make it more amenable for further processing.
</p>
<pre class="result" id="pmathSemanticSource"></pre>

<h3>Bracketed Presentation MathML generated SnuggleTeX</h3>
<p>
  This is the source of the MathML that is shown to the student, emphasising where
  inferred groupings and bracketings have been made.
</p>
<pre class="result" id="pmathBracketedSource"></pre>

<h3>Resulting Content MathML source</h3>
<p>
  This is the resulting Content MathML, created by the web service. Being able to generate
  this is criteria we use here for "making sense of the input".
</p>
<pre class="result" id="cmathSource"></pre>

<h3>Resulting Maxima code</h3>
<p>
  This is the resulting Maxima input syntax, created by the web service from the Content
  MathML. This will not always succeed as some supported Content MathML constructs can't
  be turned into Maxima equivalents.
</p>
<pre class="result" id="maximaSource"></pre>

<%@ include file="/WEB-INF/jsp/includes/footer.jspf" %>
